version: '3.1'

services:
  web:
    build: .
    expose:
      - 8014
    command: sh -c 'python /library/mysite/manage.py runserver 0.0.0.0:8014'
    volumes:
      - ./mysite:/library/mysite/
    ports:
      - 8000:8014
